language: node_js
node_js:
- "4"
- "0.12"
- "0.10"
script:
  - npm run test:cov
after_script:
  - if [[ `node --version` == *v4* ]]; then cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter; fi
